/**
 * ManageSpace Communication API
 * ManageSpace Communication API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CommunicationResponseDto {
    /**
    * Communication id
    */
    'communicationId': string;
    /**
    * Communication type.
    */
    'communicationType': CommunicationResponseDto.CommunicationTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "communicationId",
            "baseName": "communicationId",
            "type": "string"
        },
        {
            "name": "communicationType",
            "baseName": "communicationType",
            "type": "CommunicationResponseDto.CommunicationTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return CommunicationResponseDto.attributeTypeMap;
    }
}

export namespace CommunicationResponseDto {
    export enum CommunicationTypeEnum {
        MoveOutConfirmation = <any> 'moveOutConfirmation',
        ReservationConfirmation = <any> 'reservationConfirmation'
    }
}
